import type { Metadata } from 'next'
import './globals.css'
import { Providers } from './provider'
// eslint-disable-next-line
import { Fira_Code } from 'next/font/google'

const fira = Fira_Code({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DotCode',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <Head>
          <meta name="google-adsense-account" content="ca-pub-3303079752996254"></meta>
        </Head>
        <body className={`${fira.className} overflow-x-hidden bg-sto`}>
          {children}
        </body>
      </html>
    </Providers>
  )
}
